### ISSUE TITLE
fix base image to ubuntu:trusty

### ISSUE THREAD

**Issue by alexei-led** [gaia-adm/result-upload-service#1]
Fix base image and consider to install node from repository

**Comment by jaroslavl1** [comment]
fixed, we now use ubuntu:trusty

for installation of node.js, there are 3 options:
1.) use node image instead of ubuntu as base - https://registry.hub.docker.com/_/node/. Disadvantage is that we cannot control base distribution.
2.) use distribution package manager to install npm & node.js (i.e apt-get/yum) - we are more version limited
3.) download node.js, extract it ourselves. For example also https://github.com/docker-library/docs/tree/master/node does it this way, although it also does image verification.
